---
- name: "update supervisord"
  shell: "supervisorctl update"
  become: yes

- name: "restart elasticsearch"
  supervisorctl: name="elasticsearch-{{ elasticsearch_instance_name }}" state=restarted
  become: yes
