---
- name: "update supervisord"
  shell: "supervisorctl update"
  become: yes

- name: "restart elasticsearch {{ elasticsearch_instance_name }}"
  shell: "supervisorctl restart elasticsearch-{{ elasticsearch_instance_name }}"
  become: yes
